name: Deployment

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Integration"] #Its the name of an workflow
    types:
      - completed
    branches: 
      - main  

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/bun-backend:${{ github.sha }} \
                       -t ${{ secrets.DOCKERHUB_USERNAME }}/bun-backend:latest .

      - name: Login to dockerhub
        run: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push to dockerhub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/bun-backend:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/bun-backend:latest

      - name: Logout
        run: docker logout
