
name: Integration

on:
  push:
    branches: ["main"]
  pull_request: 
    branches: ["main"]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: setup bun  
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.7

      - name: install dependencies    
        run:  bun install
        
      - name: Start server
        run: | 
          bun dev &
          echo $! > server.pid
          sleep 3

      - name: Test GET 
        run: |
          curl -f http://localhost:8080  

      - name: Test POST
        run: bun test    
      
      - name: Stop server
        run: |
          kill $(cat server.pid)
